language: python
python:
  - 3.8
install:
  - pip install -q -r requirements-dev.txt codecov
script:
  - flake8
  - pytest libpythonpro_arturlauth --cov=libpythonpro_arturlauth
after_sucess:
  - codecov