language: python
python:
  - 3.8
install:
  - pip install -q pipenv codecov
  - pipenv sync --dev
script:
  - flake8
  - pytest libpythonpro_arturlauth --cov=libpythonpro_arturlauth
after_sucess:
  - codecov